// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/ci_runner.proto

package ci

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteTaskCommand_Command int32

const (
	ExecuteTaskCommand_START  ExecuteTaskCommand_Command = 0
	ExecuteTaskCommand_CANCEL ExecuteTaskCommand_Command = 1
)

// Enum value maps for ExecuteTaskCommand_Command.
var (
	ExecuteTaskCommand_Command_name = map[int32]string{
		0: "START",
		1: "CANCEL",
	}
	ExecuteTaskCommand_Command_value = map[string]int32{
		"START":  0,
		"CANCEL": 1,
	}
)

func (x ExecuteTaskCommand_Command) Enum() *ExecuteTaskCommand_Command {
	p := new(ExecuteTaskCommand_Command)
	*p = x
	return p
}

func (x ExecuteTaskCommand_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteTaskCommand_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ci_runner_proto_enumTypes[0].Descriptor()
}

func (ExecuteTaskCommand_Command) Type() protoreflect.EnumType {
	return &file_proto_ci_runner_proto_enumTypes[0]
}

func (x ExecuteTaskCommand_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteTaskCommand_Command.Descriptor instead.
func (ExecuteTaskCommand_Command) EnumDescriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{4, 0}
}

type ExecuteTaskReport_Status int32

const (
	ExecuteTaskReport_RUNNING ExecuteTaskReport_Status = 0
	ExecuteTaskReport_SUCCESS ExecuteTaskReport_Status = 1
	ExecuteTaskReport_FAILED  ExecuteTaskReport_Status = 2
)

// Enum value maps for ExecuteTaskReport_Status.
var (
	ExecuteTaskReport_Status_name = map[int32]string{
		0: "RUNNING",
		1: "SUCCESS",
		2: "FAILED",
	}
	ExecuteTaskReport_Status_value = map[string]int32{
		"RUNNING": 0,
		"SUCCESS": 1,
		"FAILED":  2,
	}
)

func (x ExecuteTaskReport_Status) Enum() *ExecuteTaskReport_Status {
	p := new(ExecuteTaskReport_Status)
	*p = x
	return p
}

func (x ExecuteTaskReport_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteTaskReport_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ci_runner_proto_enumTypes[1].Descriptor()
}

func (ExecuteTaskReport_Status) Type() protoreflect.EnumType {
	return &file_proto_ci_runner_proto_enumTypes[1]
}

func (x ExecuteTaskReport_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteTaskReport_Status.Descriptor instead.
func (ExecuteTaskReport_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{5, 0}
}

// 注册
type RegisterRunnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunnerId string `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Version  string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *RegisterRunnerReq) Reset() {
	*x = RegisterRunnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRunnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerReq) ProtoMessage() {}

func (x *RegisterRunnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerReq.ProtoReflect.Descriptor instead.
func (*RegisterRunnerReq) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRunnerReq) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterRunnerReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterRunnerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RegisterRunnerResp) Reset() {
	*x = RegisterRunnerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRunnerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerResp) ProtoMessage() {}

func (x *RegisterRunnerResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerResp.ProtoReflect.Descriptor instead.
func (*RegisterRunnerResp) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRunnerResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ==========================
// 下发任务（服务端 → 客户端）
// ==========================
type DispatchTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunnerId string `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"` // 要发给哪个 runner
}

func (x *DispatchTaskReq) Reset() {
	*x = DispatchTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskReq) ProtoMessage() {}

func (x *DispatchTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskReq.ProtoReflect.Descriptor instead.
func (*DispatchTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchTaskReq) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type DispatchTaskResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RepoUrl string `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Branch  string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Script  string `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`
}

func (x *DispatchTaskResp) Reset() {
	*x = DispatchTaskResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResp) ProtoMessage() {}

func (x *DispatchTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResp.ProtoReflect.Descriptor instead.
func (*DispatchTaskResp) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchTaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchTaskResp) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *DispatchTaskResp) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DispatchTaskResp) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// ==========================
// 执行：服务端发指令
// ==========================
type ExecuteTaskCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string                     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cmd    ExecuteTaskCommand_Command `protobuf:"varint,2,opt,name=cmd,proto3,enum=ci.ExecuteTaskCommand_Command" json:"cmd,omitempty"`
}

func (x *ExecuteTaskCommand) Reset() {
	*x = ExecuteTaskCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteTaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskCommand) ProtoMessage() {}

func (x *ExecuteTaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskCommand.ProtoReflect.Descriptor instead.
func (*ExecuteTaskCommand) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskCommand) GetCmd() ExecuteTaskCommand_Command {
	if x != nil {
		return x.Cmd
	}
	return ExecuteTaskCommand_START
}

// ==========================
// 执行：客户端上报状态/日志
// ==========================
type ExecuteTaskReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string                   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status ExecuteTaskReport_Status `protobuf:"varint,2,opt,name=status,proto3,enum=ci.ExecuteTaskReport_Status" json:"status,omitempty"`
	Log    string                   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *ExecuteTaskReport) Reset() {
	*x = ExecuteTaskReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteTaskReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskReport) ProtoMessage() {}

func (x *ExecuteTaskReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskReport.ProtoReflect.Descriptor instead.
func (*ExecuteTaskReport) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTaskReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskReport) GetStatus() ExecuteTaskReport_Status {
	if x != nil {
		return x.Status
	}
	return ExecuteTaskReport_RUNNING
}

func (x *ExecuteTaskReport) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

// ==========================
// 心跳（带任务列表）
// ==========================
type HeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunnerId       string   `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Timestamp      uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RunningTaskIds []string `protobuf:"bytes,3,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"`
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatReq) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *HeartbeatReq) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatReq) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type HeartbeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ci_runner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ci_runner_proto protoreflect.FileDescriptor

var file_proto_ci_runner_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x69, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x69, 0x22, 0x4a, 0x0a, 0x11, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x55, 0x72, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22,
	0x81, 0x01, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x30, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63,
	0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x22, 0x20, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x10, 0x01, 0x22, 0xa4, 0x01, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x22, 0x73, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x22,
	0x29, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x8f, 0x02, 0x0a, 0x0f, 0x43,
	0x69, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x15, 0x2e, 0x63, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x69, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x41, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x13, 0x2e, 0x63, 0x69, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x69, 0x2e,
	0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x30, 0x01, 0x12, 0x46, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x15, 0x2e, 0x63, 0x69, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x16,
	0x2e, 0x63, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x28, 0x01, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x09, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x10, 0x2e, 0x63, 0x69, 0x2e, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x69, 0x2e, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x63, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ci_runner_proto_rawDescOnce sync.Once
	file_proto_ci_runner_proto_rawDescData = file_proto_ci_runner_proto_rawDesc
)

func file_proto_ci_runner_proto_rawDescGZIP() []byte {
	file_proto_ci_runner_proto_rawDescOnce.Do(func() {
		file_proto_ci_runner_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ci_runner_proto_rawDescData)
	})
	return file_proto_ci_runner_proto_rawDescData
}

var file_proto_ci_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ci_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ci_runner_proto_goTypes = []interface{}{
	(ExecuteTaskCommand_Command)(0), // 0: ci.ExecuteTaskCommand.Command
	(ExecuteTaskReport_Status)(0),   // 1: ci.ExecuteTaskReport.Status
	(*RegisterRunnerReq)(nil),       // 2: ci.RegisterRunnerReq
	(*RegisterRunnerResp)(nil),      // 3: ci.RegisterRunnerResp
	(*DispatchTaskReq)(nil),         // 4: ci.DispatchTaskReq
	(*DispatchTaskResp)(nil),        // 5: ci.DispatchTaskResp
	(*ExecuteTaskCommand)(nil),      // 6: ci.ExecuteTaskCommand
	(*ExecuteTaskReport)(nil),       // 7: ci.ExecuteTaskReport
	(*HeartbeatReq)(nil),            // 8: ci.HeartbeatReq
	(*HeartbeatResp)(nil),           // 9: ci.HeartbeatResp
}
var file_proto_ci_runner_proto_depIdxs = []int32{
	0, // 0: ci.ExecuteTaskCommand.cmd:type_name -> ci.ExecuteTaskCommand.Command
	1, // 1: ci.ExecuteTaskReport.status:type_name -> ci.ExecuteTaskReport.Status
	2, // 2: ci.CiRunnerService.RegisterRunner:input_type -> ci.RegisterRunnerReq
	4, // 3: ci.CiRunnerService.DispatchTaskStream:input_type -> ci.DispatchTaskReq
	7, // 4: ci.CiRunnerService.ExecuteTaskStream:input_type -> ci.ExecuteTaskReport
	8, // 5: ci.CiRunnerService.Heartbeat:input_type -> ci.HeartbeatReq
	3, // 6: ci.CiRunnerService.RegisterRunner:output_type -> ci.RegisterRunnerResp
	5, // 7: ci.CiRunnerService.DispatchTaskStream:output_type -> ci.DispatchTaskResp
	6, // 8: ci.CiRunnerService.ExecuteTaskStream:output_type -> ci.ExecuteTaskCommand
	9, // 9: ci.CiRunnerService.Heartbeat:output_type -> ci.HeartbeatResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ci_runner_proto_init() }
func file_proto_ci_runner_proto_init() {
	if File_proto_ci_runner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ci_runner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRunnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRunnerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchTaskResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteTaskCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteTaskReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ci_runner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ci_runner_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ci_runner_proto_goTypes,
		DependencyIndexes: file_proto_ci_runner_proto_depIdxs,
		EnumInfos:         file_proto_ci_runner_proto_enumTypes,
		MessageInfos:      file_proto_ci_runner_proto_msgTypes,
	}.Build()
	File_proto_ci_runner_proto = out.File
	file_proto_ci_runner_proto_rawDesc = nil
	file_proto_ci_runner_proto_goTypes = nil
	file_proto_ci_runner_proto_depIdxs = nil
}
