// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/ci_runner.proto

package ci

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CiRunnerService_RegisterRunner_FullMethodName     = "/ci.CiRunnerService/RegisterRunner"
	CiRunnerService_DispatchTaskStream_FullMethodName = "/ci.CiRunnerService/DispatchTaskStream"
	CiRunnerService_ExecuteTaskStream_FullMethodName  = "/ci.CiRunnerService/ExecuteTaskStream"
	CiRunnerService_Heartbeat_FullMethodName          = "/ci.CiRunnerService/Heartbeat"
)

// CiRunnerServiceClient is the client API for CiRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CiRunnerServiceClient interface {
	RegisterRunner(ctx context.Context, in *RegisterRunnerReq, opts ...grpc.CallOption) (*RegisterRunnerResp, error)
	DispatchTaskStream(ctx context.Context, in *DispatchTaskReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchTaskResp], error)
	ExecuteTaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteTaskReport, ExecuteTaskCommand], error)
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error)
}

type ciRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCiRunnerServiceClient(cc grpc.ClientConnInterface) CiRunnerServiceClient {
	return &ciRunnerServiceClient{cc}
}

func (c *ciRunnerServiceClient) RegisterRunner(ctx context.Context, in *RegisterRunnerReq, opts ...grpc.CallOption) (*RegisterRunnerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRunnerResp)
	err := c.cc.Invoke(ctx, CiRunnerService_RegisterRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciRunnerServiceClient) DispatchTaskStream(ctx context.Context, in *DispatchTaskReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchTaskResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CiRunnerService_ServiceDesc.Streams[0], CiRunnerService_DispatchTaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchTaskReq, DispatchTaskResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CiRunnerService_DispatchTaskStreamClient = grpc.ServerStreamingClient[DispatchTaskResp]

func (c *ciRunnerServiceClient) ExecuteTaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteTaskReport, ExecuteTaskCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CiRunnerService_ServiceDesc.Streams[1], CiRunnerService_ExecuteTaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteTaskReport, ExecuteTaskCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CiRunnerService_ExecuteTaskStreamClient = grpc.BidiStreamingClient[ExecuteTaskReport, ExecuteTaskCommand]

func (c *ciRunnerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResp)
	err := c.cc.Invoke(ctx, CiRunnerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CiRunnerServiceServer is the server API for CiRunnerService service.
// All implementations must embed UnimplementedCiRunnerServiceServer
// for forward compatibility.
type CiRunnerServiceServer interface {
	RegisterRunner(context.Context, *RegisterRunnerReq) (*RegisterRunnerResp, error)
	DispatchTaskStream(*DispatchTaskReq, grpc.ServerStreamingServer[DispatchTaskResp]) error
	ExecuteTaskStream(grpc.BidiStreamingServer[ExecuteTaskReport, ExecuteTaskCommand]) error
	Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error)
	mustEmbedUnimplementedCiRunnerServiceServer()
}

// UnimplementedCiRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCiRunnerServiceServer struct{}

func (UnimplementedCiRunnerServiceServer) RegisterRunner(context.Context, *RegisterRunnerReq) (*RegisterRunnerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRunner not implemented")
}
func (UnimplementedCiRunnerServiceServer) DispatchTaskStream(*DispatchTaskReq, grpc.ServerStreamingServer[DispatchTaskResp]) error {
	return status.Error(codes.Unimplemented, "method DispatchTaskStream not implemented")
}
func (UnimplementedCiRunnerServiceServer) ExecuteTaskStream(grpc.BidiStreamingServer[ExecuteTaskReport, ExecuteTaskCommand]) error {
	return status.Error(codes.Unimplemented, "method ExecuteTaskStream not implemented")
}
func (UnimplementedCiRunnerServiceServer) Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCiRunnerServiceServer) mustEmbedUnimplementedCiRunnerServiceServer() {}
func (UnimplementedCiRunnerServiceServer) testEmbeddedByValue()                         {}

// UnsafeCiRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CiRunnerServiceServer will
// result in compilation errors.
type UnsafeCiRunnerServiceServer interface {
	mustEmbedUnimplementedCiRunnerServiceServer()
}

func RegisterCiRunnerServiceServer(s grpc.ServiceRegistrar, srv CiRunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedCiRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CiRunnerService_ServiceDesc, srv)
}

func _CiRunnerService_RegisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRunnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiRunnerServiceServer).RegisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiRunnerService_RegisterRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiRunnerServiceServer).RegisterRunner(ctx, req.(*RegisterRunnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiRunnerService_DispatchTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchTaskReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CiRunnerServiceServer).DispatchTaskStream(m, &grpc.GenericServerStream[DispatchTaskReq, DispatchTaskResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CiRunnerService_DispatchTaskStreamServer = grpc.ServerStreamingServer[DispatchTaskResp]

func _CiRunnerService_ExecuteTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CiRunnerServiceServer).ExecuteTaskStream(&grpc.GenericServerStream[ExecuteTaskReport, ExecuteTaskCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CiRunnerService_ExecuteTaskStreamServer = grpc.BidiStreamingServer[ExecuteTaskReport, ExecuteTaskCommand]

func _CiRunnerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiRunnerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiRunnerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiRunnerServiceServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CiRunnerService_ServiceDesc is the grpc.ServiceDesc for CiRunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CiRunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ci.CiRunnerService",
	HandlerType: (*CiRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRunner",
			Handler:    _CiRunnerService_RegisterRunner_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CiRunnerService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DispatchTaskStream",
			Handler:       _CiRunnerService_DispatchTaskStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteTaskStream",
			Handler:       _CiRunnerService_ExecuteTaskStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ci_runner.proto",
}
