// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ci

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CiRunnerServiceClient is the client API for CiRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CiRunnerServiceClient interface {
	RegisterRunner(ctx context.Context, in *RegisterRunnerReq, opts ...grpc.CallOption) (*RegisterRunnerResp, error)
	// ✅ 正确：服务端流 → 服务端主动下发任务给客户端
	DispatchTaskStream(ctx context.Context, in *DispatchTaskReq, opts ...grpc.CallOption) (CiRunnerService_DispatchTaskStreamClient, error)
	// 双向流：执行日志上报
	ExecuteTaskStream(ctx context.Context, opts ...grpc.CallOption) (CiRunnerService_ExecuteTaskStreamClient, error)
	// 心跳
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error)
}

type ciRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCiRunnerServiceClient(cc grpc.ClientConnInterface) CiRunnerServiceClient {
	return &ciRunnerServiceClient{cc}
}

func (c *ciRunnerServiceClient) RegisterRunner(ctx context.Context, in *RegisterRunnerReq, opts ...grpc.CallOption) (*RegisterRunnerResp, error) {
	out := new(RegisterRunnerResp)
	err := c.cc.Invoke(ctx, "/ci.CiRunnerService/RegisterRunner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ciRunnerServiceClient) DispatchTaskStream(ctx context.Context, in *DispatchTaskReq, opts ...grpc.CallOption) (CiRunnerService_DispatchTaskStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CiRunnerService_ServiceDesc.Streams[0], "/ci.CiRunnerService/DispatchTaskStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &ciRunnerServiceDispatchTaskStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CiRunnerService_DispatchTaskStreamClient interface {
	Recv() (*DispatchTaskResp, error)
	grpc.ClientStream
}

type ciRunnerServiceDispatchTaskStreamClient struct {
	grpc.ClientStream
}

func (x *ciRunnerServiceDispatchTaskStreamClient) Recv() (*DispatchTaskResp, error) {
	m := new(DispatchTaskResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ciRunnerServiceClient) ExecuteTaskStream(ctx context.Context, opts ...grpc.CallOption) (CiRunnerService_ExecuteTaskStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CiRunnerService_ServiceDesc.Streams[1], "/ci.CiRunnerService/ExecuteTaskStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &ciRunnerServiceExecuteTaskStreamClient{stream}
	return x, nil
}

type CiRunnerService_ExecuteTaskStreamClient interface {
	Send(*ExecuteTaskReport) error
	Recv() (*ExecuteTaskCommand, error)
	grpc.ClientStream
}

type ciRunnerServiceExecuteTaskStreamClient struct {
	grpc.ClientStream
}

func (x *ciRunnerServiceExecuteTaskStreamClient) Send(m *ExecuteTaskReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ciRunnerServiceExecuteTaskStreamClient) Recv() (*ExecuteTaskCommand, error) {
	m := new(ExecuteTaskCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ciRunnerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error) {
	out := new(HeartbeatResp)
	err := c.cc.Invoke(ctx, "/ci.CiRunnerService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CiRunnerServiceServer is the server API for CiRunnerService service.
// All implementations must embed UnimplementedCiRunnerServiceServer
// for forward compatibility
type CiRunnerServiceServer interface {
	RegisterRunner(context.Context, *RegisterRunnerReq) (*RegisterRunnerResp, error)
	// ✅ 正确：服务端流 → 服务端主动下发任务给客户端
	DispatchTaskStream(*DispatchTaskReq, CiRunnerService_DispatchTaskStreamServer) error
	// 双向流：执行日志上报
	ExecuteTaskStream(CiRunnerService_ExecuteTaskStreamServer) error
	// 心跳
	Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error)
	mustEmbedUnimplementedCiRunnerServiceServer()
}

// UnimplementedCiRunnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCiRunnerServiceServer struct {
}

func (UnimplementedCiRunnerServiceServer) RegisterRunner(context.Context, *RegisterRunnerReq) (*RegisterRunnerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRunner not implemented")
}
func (UnimplementedCiRunnerServiceServer) DispatchTaskStream(*DispatchTaskReq, CiRunnerService_DispatchTaskStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DispatchTaskStream not implemented")
}
func (UnimplementedCiRunnerServiceServer) ExecuteTaskStream(CiRunnerService_ExecuteTaskStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteTaskStream not implemented")
}
func (UnimplementedCiRunnerServiceServer) Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCiRunnerServiceServer) mustEmbedUnimplementedCiRunnerServiceServer() {}

// UnsafeCiRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CiRunnerServiceServer will
// result in compilation errors.
type UnsafeCiRunnerServiceServer interface {
	mustEmbedUnimplementedCiRunnerServiceServer()
}

func RegisterCiRunnerServiceServer(s grpc.ServiceRegistrar, srv CiRunnerServiceServer) {
	s.RegisterService(&CiRunnerService_ServiceDesc, srv)
}

func _CiRunnerService_RegisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRunnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiRunnerServiceServer).RegisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.CiRunnerService/RegisterRunner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiRunnerServiceServer).RegisterRunner(ctx, req.(*RegisterRunnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CiRunnerService_DispatchTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchTaskReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CiRunnerServiceServer).DispatchTaskStream(m, &ciRunnerServiceDispatchTaskStreamServer{stream})
}

type CiRunnerService_DispatchTaskStreamServer interface {
	Send(*DispatchTaskResp) error
	grpc.ServerStream
}

type ciRunnerServiceDispatchTaskStreamServer struct {
	grpc.ServerStream
}

func (x *ciRunnerServiceDispatchTaskStreamServer) Send(m *DispatchTaskResp) error {
	return x.ServerStream.SendMsg(m)
}

func _CiRunnerService_ExecuteTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CiRunnerServiceServer).ExecuteTaskStream(&ciRunnerServiceExecuteTaskStreamServer{stream})
}

type CiRunnerService_ExecuteTaskStreamServer interface {
	Send(*ExecuteTaskCommand) error
	Recv() (*ExecuteTaskReport, error)
	grpc.ServerStream
}

type ciRunnerServiceExecuteTaskStreamServer struct {
	grpc.ServerStream
}

func (x *ciRunnerServiceExecuteTaskStreamServer) Send(m *ExecuteTaskCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ciRunnerServiceExecuteTaskStreamServer) Recv() (*ExecuteTaskReport, error) {
	m := new(ExecuteTaskReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CiRunnerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiRunnerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.CiRunnerService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiRunnerServiceServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CiRunnerService_ServiceDesc is the grpc.ServiceDesc for CiRunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CiRunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ci.CiRunnerService",
	HandlerType: (*CiRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRunner",
			Handler:    _CiRunnerService_RegisterRunner_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CiRunnerService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DispatchTaskStream",
			Handler:       _CiRunnerService_DispatchTaskStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteTaskStream",
			Handler:       _CiRunnerService_ExecuteTaskStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ci_runner.proto",
}
