// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ci_runner.proto

package ci

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteTaskCommand_Command int32

const (
	ExecuteTaskCommand_START  ExecuteTaskCommand_Command = 0
	ExecuteTaskCommand_CANCEL ExecuteTaskCommand_Command = 1
)

// Enum value maps for ExecuteTaskCommand_Command.
var (
	ExecuteTaskCommand_Command_name = map[int32]string{
		0: "START",
		1: "CANCEL",
	}
	ExecuteTaskCommand_Command_value = map[string]int32{
		"START":  0,
		"CANCEL": 1,
	}
)

func (x ExecuteTaskCommand_Command) Enum() *ExecuteTaskCommand_Command {
	p := new(ExecuteTaskCommand_Command)
	*p = x
	return p
}

func (x ExecuteTaskCommand_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteTaskCommand_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ci_runner_proto_enumTypes[0].Descriptor()
}

func (ExecuteTaskCommand_Command) Type() protoreflect.EnumType {
	return &file_proto_ci_runner_proto_enumTypes[0]
}

func (x ExecuteTaskCommand_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteTaskCommand_Command.Descriptor instead.
func (ExecuteTaskCommand_Command) EnumDescriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{4, 0}
}

type ExecuteTaskReport_Status int32

const (
	ExecuteTaskReport_RUNNING ExecuteTaskReport_Status = 0
	ExecuteTaskReport_SUCCESS ExecuteTaskReport_Status = 1
	ExecuteTaskReport_FAILED  ExecuteTaskReport_Status = 2
)

// Enum value maps for ExecuteTaskReport_Status.
var (
	ExecuteTaskReport_Status_name = map[int32]string{
		0: "RUNNING",
		1: "SUCCESS",
		2: "FAILED",
	}
	ExecuteTaskReport_Status_value = map[string]int32{
		"RUNNING": 0,
		"SUCCESS": 1,
		"FAILED":  2,
	}
)

func (x ExecuteTaskReport_Status) Enum() *ExecuteTaskReport_Status {
	p := new(ExecuteTaskReport_Status)
	*p = x
	return p
}

func (x ExecuteTaskReport_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteTaskReport_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ci_runner_proto_enumTypes[1].Descriptor()
}

func (ExecuteTaskReport_Status) Type() protoreflect.EnumType {
	return &file_proto_ci_runner_proto_enumTypes[1]
}

func (x ExecuteTaskReport_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteTaskReport_Status.Descriptor instead.
func (ExecuteTaskReport_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{5, 0}
}

type RegisterRunnerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Cpu           int32                  `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerReq) Reset() {
	*x = RegisterRunnerReq{}
	mi := &file_proto_ci_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerReq) ProtoMessage() {}

func (x *RegisterRunnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerReq.ProtoReflect.Descriptor instead.
func (*RegisterRunnerReq) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRunnerReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegisterRunnerReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRunnerReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRunnerReq) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRunnerReq) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

type RegisterRunnerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerResp) Reset() {
	*x = RegisterRunnerResp{}
	mi := &file_proto_ci_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerResp) ProtoMessage() {}

func (x *RegisterRunnerResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerResp.ProtoReflect.Descriptor instead.
func (*RegisterRunnerResp) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRunnerResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DispatchTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskReq) Reset() {
	*x = DispatchTaskReq{}
	mi := &file_proto_ci_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskReq) ProtoMessage() {}

func (x *DispatchTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskReq.ProtoReflect.Descriptor instead.
func (*DispatchTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchTaskReq) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type DispatchTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Script        string                 `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResp) Reset() {
	*x = DispatchTaskResp{}
	mi := &file_proto_ci_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResp) ProtoMessage() {}

func (x *DispatchTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResp.ProtoReflect.Descriptor instead.
func (*DispatchTaskResp) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchTaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchTaskResp) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *DispatchTaskResp) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DispatchTaskResp) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type ExecuteTaskCommand struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TaskId        string                     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cmd           ExecuteTaskCommand_Command `protobuf:"varint,2,opt,name=cmd,proto3,enum=ci.ExecuteTaskCommand_Command" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskCommand) Reset() {
	*x = ExecuteTaskCommand{}
	mi := &file_proto_ci_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskCommand) ProtoMessage() {}

func (x *ExecuteTaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskCommand.ProtoReflect.Descriptor instead.
func (*ExecuteTaskCommand) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskCommand) GetCmd() ExecuteTaskCommand_Command {
	if x != nil {
		return x.Cmd
	}
	return ExecuteTaskCommand_START
}

type ExecuteTaskReport struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TaskId        string                   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ExecuteTaskReport_Status `protobuf:"varint,2,opt,name=status,proto3,enum=ci.ExecuteTaskReport_Status" json:"status,omitempty"`
	Log           string                   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskReport) Reset() {
	*x = ExecuteTaskReport{}
	mi := &file_proto_ci_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskReport) ProtoMessage() {}

func (x *ExecuteTaskReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskReport.ProtoReflect.Descriptor instead.
func (*ExecuteTaskReport) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTaskReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskReport) GetStatus() ExecuteTaskReport_Status {
	if x != nil {
		return x.Status
	}
	return ExecuteTaskReport_RUNNING
}

func (x *ExecuteTaskReport) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_proto_ci_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_proto_ci_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ci_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_proto_ci_runner_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ci_runner_proto protoreflect.FileDescriptor

const file_proto_ci_runner_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ci_runner.proto\x12\x02ci\"w\n" +
	"\x11RegisterRunnerReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\x05R\x03cpu\".\n" +
	"\x12RegisterRunnerResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x0fDispatchTaskReq\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"v\n" +
	"\x10DispatchTaskResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x16\n" +
	"\x06script\x18\x04 \x01(\tR\x06script\"\x81\x01\n" +
	"\x12ExecuteTaskCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x03cmd\x18\x02 \x01(\x0e2\x1e.ci.ExecuteTaskCommand.CommandR\x03cmd\" \n" +
	"\aCommand\x12\t\n" +
	"\x05START\x10\x00\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x01\"\xa4\x01\n" +
	"\x11ExecuteTaskReport\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.ci.ExecuteTaskReport.StatusR\x06status\x12\x10\n" +
	"\x03log\x18\x03 \x01(\tR\x03log\".\n" +
	"\x06Status\x12\v\n" +
	"\aRUNNING\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\"\"\n" +
	"\fHeartbeatReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\")\n" +
	"\rHeartbeatResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8f\x02\n" +
	"\x0fCiRunnerService\x12?\n" +
	"\x0eRegisterRunner\x12\x15.ci.RegisterRunnerReq\x1a\x16.ci.RegisterRunnerResp\x12A\n" +
	"\x12DispatchTaskStream\x12\x13.ci.DispatchTaskReq\x1a\x14.ci.DispatchTaskResp0\x01\x12F\n" +
	"\x11ExecuteTaskStream\x12\x15.ci.ExecuteTaskReport\x1a\x16.ci.ExecuteTaskCommand(\x010\x01\x120\n" +
	"\tHeartbeat\x12\x10.ci.HeartbeatReq\x1a\x11.ci.HeartbeatRespB\x06Z\x04./cib\x06proto3"

var (
	file_proto_ci_runner_proto_rawDescOnce sync.Once
	file_proto_ci_runner_proto_rawDescData []byte
)

func file_proto_ci_runner_proto_rawDescGZIP() []byte {
	file_proto_ci_runner_proto_rawDescOnce.Do(func() {
		file_proto_ci_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ci_runner_proto_rawDesc), len(file_proto_ci_runner_proto_rawDesc)))
	})
	return file_proto_ci_runner_proto_rawDescData
}

var file_proto_ci_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ci_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ci_runner_proto_goTypes = []any{
	(ExecuteTaskCommand_Command)(0), // 0: ci.ExecuteTaskCommand.Command
	(ExecuteTaskReport_Status)(0),   // 1: ci.ExecuteTaskReport.Status
	(*RegisterRunnerReq)(nil),       // 2: ci.RegisterRunnerReq
	(*RegisterRunnerResp)(nil),      // 3: ci.RegisterRunnerResp
	(*DispatchTaskReq)(nil),         // 4: ci.DispatchTaskReq
	(*DispatchTaskResp)(nil),        // 5: ci.DispatchTaskResp
	(*ExecuteTaskCommand)(nil),      // 6: ci.ExecuteTaskCommand
	(*ExecuteTaskReport)(nil),       // 7: ci.ExecuteTaskReport
	(*HeartbeatReq)(nil),            // 8: ci.HeartbeatReq
	(*HeartbeatResp)(nil),           // 9: ci.HeartbeatResp
}
var file_proto_ci_runner_proto_depIdxs = []int32{
	0, // 0: ci.ExecuteTaskCommand.cmd:type_name -> ci.ExecuteTaskCommand.Command
	1, // 1: ci.ExecuteTaskReport.status:type_name -> ci.ExecuteTaskReport.Status
	2, // 2: ci.CiRunnerService.RegisterRunner:input_type -> ci.RegisterRunnerReq
	4, // 3: ci.CiRunnerService.DispatchTaskStream:input_type -> ci.DispatchTaskReq
	7, // 4: ci.CiRunnerService.ExecuteTaskStream:input_type -> ci.ExecuteTaskReport
	8, // 5: ci.CiRunnerService.Heartbeat:input_type -> ci.HeartbeatReq
	3, // 6: ci.CiRunnerService.RegisterRunner:output_type -> ci.RegisterRunnerResp
	5, // 7: ci.CiRunnerService.DispatchTaskStream:output_type -> ci.DispatchTaskResp
	6, // 8: ci.CiRunnerService.ExecuteTaskStream:output_type -> ci.ExecuteTaskCommand
	9, // 9: ci.CiRunnerService.Heartbeat:output_type -> ci.HeartbeatResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ci_runner_proto_init() }
func file_proto_ci_runner_proto_init() {
	if File_proto_ci_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ci_runner_proto_rawDesc), len(file_proto_ci_runner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ci_runner_proto_goTypes,
		DependencyIndexes: file_proto_ci_runner_proto_depIdxs,
		EnumInfos:         file_proto_ci_runner_proto_enumTypes,
		MessageInfos:      file_proto_ci_runner_proto_msgTypes,
	}.Build()
	File_proto_ci_runner_proto = out.File
	file_proto_ci_runner_proto_goTypes = nil
	file_proto_ci_runner_proto_depIdxs = nil
}
